config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  devise_for :users

  devise_scope :user do
      match "/backoffice"  => "devise/sessions#new", via: [:get], as: :unauthenticated_root
      match "signout" => "devise/sessions#destroy", via: [:delete]
  end

  namespace :backoffice do
    resources :partner_users, except: [:destroy] do
      member do
        get   '/add_permission', to: 'partner_users#add_permission', as: 'add_permission'
        post  '/save_permission', to: 'partner_users#save_permission', as: 'save_permission'
        delete '/permission/:user_permit_id', to: 'partner_users#delete_permission', as: 'delete_permission'
      end
    end
    resources :products, except: [:destroy]
    resources :orders, only: [:index, :show]
    resources :carts, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      # Product
      get 'lists', to: 'products#lists', as: 'list_of_products'
      get 'detail/:id', to: 'products#detail', as: 'detail_of_product'

      # Order
      post 'add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart_order'
      get  'cart/detail/:user_id', to: 'orders#cart_detail', as: 'cart_detail'
      post 'cart/checkout', to: 'orders#checkout', as: 'checkout'
    end
  end
end

app/models/partner_user.rb
class PartnerUser < ApplicationRecord

  before_create :set_uid_and_auth_token

  has_many :user_permits, as: :source
  belongs_to :cart, required: false
  belongs_to :order, required: false

  private

  def set_uid_and_auth_token
    self.uid = SecureRandom.uuid unless self.uid.present?
    self.auth_token = AuthEngine.encode({uid: self.uid, klass: self.class.to_s}) unless self.auth_token.present?
  end
end

app/controllers/backoffice/carts_controller.rb
module Backoffice
  class CartsController < ApplicationController
    before_action :authenticate_user!

    def index
      @carts = Cart.all
    end

    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/backoffice/orders_controller.rb
module Backoffice
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @orders = Order.all
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/backoffice/partner_users_controller.rb
module Backoffice
  class PartnerUsersController < ApplicationController

    before_action :authenticate_user!

    def index
      @partner_users = PartnerUser.all
    end

    def show
      @partner_user = PartnerUser.find(params[:id])
    end

    def new
      @partner_user = PartnerUser.new
      @url = backoffice_partner_users_path(@partner_user)
    end

    def create
      @partner_user = PartnerUser.new(create_params)
      if @partner_user.save
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully created.'
      else
        @url = backoffice_partner_users_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :new
      end
    end

    def edit
      @partner_user = PartnerUser.find(params[:id])
      @url = backoffice_partner_user_path(@partner_user)
    end

    def update
      @partner_user = PartnerUser.find(params[:id])
      if @partner_user.update(update_params)
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully updated.'
      else
        @url = backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :edit
      end
    end

    def add_permission
      @partner_user = PartnerUser.find(params[:id])
      @permission_options = Permission.all.collect{ |p| [p.name, p.id]}
      @url = save_permission_backoffice_partner_user_path(@partner_user)
    end

    def save_permission
      @partner_user = PartnerUser.find(params[:id])
      permission = Permission.find(params[:permission_id])

      if permission.present?
        user_permit = UserPermit.find_by(source: @partner_user, permission: permission)
        if user_permit.present?
          redirect_to backoffice_partner_user_path(@partner_user), notice: "Partner User was have assigned APIs Permission for #{permission.name} before."
        else
          user_permit = UserPermit.new(source: @partner_user, permission: permission)
          if user_permit.save
            redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully added new APIs Permission.'
          else
            @url = save_permission_backoffice_partner_user_path(@partner_user)
            flash[:alert] = user_permit.errors.full_messages
            render :add_permission
          end
        end
      else
        @url = save_permission_backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :add_permission
      end
    end

    def delete_permission
      @partner_user = PartnerUser.find(params[:id])
      user_permit = UserPermit.find(params[:user_permit_id])
      if user_permit.present? && user_permit.source == @partner_user
        if user_permit.delete
          redirect_to backoffice_partner_user_path(@partner_user), notice: 'Successfully to delete APIs Permission from Partner User.'
        else
          redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
        end
      else
        redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
      end
    end

    private

    def create_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

    def update_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

  end
end

app/controllers/backoffice/products_controller.rb
module Backoffice
  class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
      @products = Product.all.order(updated_at: :desc)
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
      @url = backoffice_products_path(@product)
    end

    def create
      @product = Product.new(create_params)
      if @product.save
          redirect_to backoffice_product_path(@product), notice: 'Product was successfully created.'
      else
        @url = backoffice_products_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :new
      end
    end

    def edit
      @product = Product.find(params[:id])
      @url = backoffice_product_path(@product)
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(update_params)
        redirect_to backoffice_product_path(@product), notice: 'Product was successfully updated.'
      else
        @url = backoffice_product_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :edit
      end
    end

    private

    def create_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end

    def update_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end
  end
end

app/views/backoffice/partner_users/_form.html.erb
<%= form_for(@partner_user, url: @url, html: {class: 'form-horizontal'}) do |f| %>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Fullname</label>
    <div class="col-sm-10">
      <%= f.text_field :fullname, autofocus: true, class: 'form-control', placeholder: 'Fullname', required: true %>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Phone Number</label>
    <div class="col-sm-10">
      <%= f.text_field :phone, autofocus: true, class: 'form-control', placeholder: 'Phone Number', required: true %>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Address</label>
    <div class="col-sm-10">
      <%= f.text_field :address, autofocus: true, class: 'form-control', placeholder: 'Address', required: true %>
    </div>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %> <%= link_to 'Cancel', backoffice_partner_users_path, class: 'btn btn-secondary' %>
<% end %>

app/views/backoffice/partner_users/add_permission.html.erb
<h1 class="mt-4">Partner User</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Partner User</li>
  <li class="breadcrumb-item"><%= @partner_user.fullname %></li>
  <li class="breadcrumb-item active">Add APIs Permission</li>
</ol>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Add APIs Permission</div>
      <div class="card-body">
      <%= form_with url: @url do |f| %>
        <div class="mb-3 row">
          <label class="col-sm-2 col-form-label">Fullname</label>
          <div class="col-sm-10">
            <%= f.text_field :fullname, class: 'form-control', placeholder: @partner_user.fullname, disabled: true %>
          </div>
        </div>

        <div class="mb-3 row">
          <label class="col-sm-2 col-form-label">Permission</label>
          <div class="col-sm-10">
            <%= f.select :permission_id, @permission_options, { prompt: 'Select Permission' }, {class: 'form-control'} %>
          </div>
        </div>

        <%= f.submit 'Save', class: 'btn btn-primary' %> <%= link_to 'Cancel', backoffice_partner_user_path(@partner_user), class: 'btn btn-secondary' %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/partner_users/edit.html.erb
<h1 class="mt-4">Partner User</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Partner User</li>
  <li class="breadcrumb-item"><%= @partner_user.fullname %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Edit</div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/partner_users/index.html.erb
<h1 class="mt-4">Partner User</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item active">Partner User</li>
</ol>

<p><%= link_to 'New', new_backoffice_partner_user_path, class: 'btn btn-primary' %></p>

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    List of Partner User
  </div>

  <div class="card-body">

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Fullname</th>
          <th scope="col">Address</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Created At</th>
          <th scope="col">Updated At</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @partner_users.each_with_index do |partner_user, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= partner_user.fullname %></td>
          <td><%= partner_user.address %></td>
          <td><%= partner_user.phone %></td>
          <td><%= partner_user.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td><%= partner_user.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td> <%= link_to 'Show', backoffice_partner_user_path(partner_user)%> | <%= link_to 'Edit', edit_backoffice_partner_user_path(partner_user)%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/backoffice/partner_users/new.html.erb
<h1 class="mt-4">Partner User</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Partner User</li>
  <li class="breadcrumb-item active">New</li>
</ol>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">New</div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/partner_users/show.html.erb
<h1 class="mt-4">Partner User</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Partner User</li>
  <li class="breadcrumb-item active"><%= @partner_user.fullname %></li>
</ol>

<p>
  <%= link_to 'New', new_backoffice_partner_user_path, class: 'btn btn-primary' %>
  <%= link_to 'Edit', edit_backoffice_partner_user_path(@partner_user), class: 'btn btn-warning' %>
  <%= link_to 'Add APIs Permission', add_permission_backoffice_partner_user_path(@partner_user), class: 'btn btn-info' %>

</p>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Detail</div>
      <div class="card-body">
        <table class="table table-borderless">
        <thead>
          <tr>
            <td nowrap>Fullname</td>
            <td><%= @partner_user.fullname %></td>
          </tr>
          <tr>
            <td nowrap>Phone Number</td>
            <td><%= @partner_user.phone %></td>
          </tr>
          <tr>
            <td nowrap>Address</td>
            <td><%= @partner_user.address %></td>
          </tr>
          <tr>
            <td nowrap>UID</td>
            <td><%= @partner_user.uid %></td>
          </tr>
          <tr>
            <td nowrap>Auth Token</td>
            <td style="word-break: break-all;"><%= @partner_user.auth_token %></td>
          </tr>
          <tr>
            <td>Created At</td>
            <td><%= @partner_user.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
          <tr>
            <td>Updated At</td>
            <td><%= @partner_user.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
        </thead>
      </table>
      </div>
    </div>
  </div>

  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">APIs Permissions</div>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Code</th>
              <th scope="col">Name</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @partner_user.user_permits.each_with_index do |user_permit, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= user_permit.permission.code %></td>
                <td><%= user_permit.permission.name %></td>
                <td>
                  <%= link_to 'Delete', delete_permission_backoffice_partner_user_path(@partner_user, user_permit), method: :delete, class: 'btn btn-danger btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>