config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  devise_for :users

  devise_scope :user do
      match "/backoffice"  => "devise/sessions#new", via: [:get], as: :unauthenticated_root
      match "signout" => "devise/sessions#destroy", via: [:delete]
  end

  namespace :backoffice do
    resources :partner_users, except: [:destroy] do
      member do
        get   '/add_permission', to: 'partner_users#add_permission', as: 'add_permission'
        post  '/save_permission', to: 'partner_users#save_permission', as: 'save_permission'
        delete '/permission/:user_permit_id', to: 'partner_users#delete_permission', as: 'delete_permission'
      end
    end
    resources :products, except: [:destroy]
    resources :orders, only: [:index, :show]
    resources :carts, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      # Product
      get 'lists', to: 'products#lists', as: 'list_of_products'
      get 'detail/:id', to: 'products#detail', as: 'detail_of_product'

      # Order
      post 'add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart_order'
      get  'cart/detail/:user_id', to: 'orders#cart_detail', as: 'cart_detail'
      post 'cart/checkout', to: 'orders#checkout', as: 'checkout'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer, polymorphic: true
  has_many :order_items, inverse_of: :order, dependent: :destroy

end

app/controllers/api/v1/orders_controller.rb
module Api
  module V1
    class OrdersController < Api::V1::BaseController

      before_action :authenticate_user, :authorize_request

      def initialize
        super
        @order_service = ::V1::OrderService.new
      end

      def add_to_cart
        if add_to_cart_params[:user_id].present? && add_to_cart_params[:product_id].present?
          render_json_result @order_service.add_to_cart(add_to_cart_params[:user_id], add_to_cart_params[:product_id])
        else
          render_json_bad_request
        end
      end

      def cart_detail
        if cart_detail_params[:user_id]
          render_json_result @order_service.cart_detail(current_user.id.to_s, cart_detail_params[:user_id])
        else
          render_json_bad_request
        end
      end

      def checkout
        if checkout_params[:user_id].present?
          render_json_result @order_service.checkout(current_user.id.to_s, checkout_params[:user_id])
        else
          render_json_bad_request
        end
      end

      private

      def authorize_request
        authorize_request_for 'Order'
      end

      def add_to_cart_params
        params.permit(:user_id, :product_id)
      end

      def cart_detail_params
        params.permit(:user_id)
      end

      def checkout_params
        params.permit(:user_id)
      end
    end
  end
end

app/controllers/backoffice/carts_controller.rb
module Backoffice
  class CartsController < ApplicationController
    before_action :authenticate_user!

    def index
      @carts = Cart.all
    end

    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/backoffice/orders_controller.rb
module Backoffice
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @orders = Order.all
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/backoffice/partner_users_controller.rb
module Backoffice
  class PartnerUsersController < ApplicationController

    before_action :authenticate_user!

    def index
      @partner_users = PartnerUser.all
    end

    def show
      @partner_user = PartnerUser.find(params[:id])
    end

    def new
      @partner_user = PartnerUser.new
      @url = backoffice_partner_users_path(@partner_user)
    end

    def create
      @partner_user = PartnerUser.new(create_params)
      if @partner_user.save
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully created.'
      else
        @url = backoffice_partner_users_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :new
      end
    end

    def edit
      @partner_user = PartnerUser.find(params[:id])
      @url = backoffice_partner_user_path(@partner_user)
    end

    def update
      @partner_user = PartnerUser.find(params[:id])
      if @partner_user.update(update_params)
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully updated.'
      else
        @url = backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :edit
      end
    end

    def add_permission
      @partner_user = PartnerUser.find(params[:id])
      @permission_options = Permission.all.collect{ |p| [p.name, p.id]}
      @url = save_permission_backoffice_partner_user_path(@partner_user)
    end

    def save_permission
      @partner_user = PartnerUser.find(params[:id])
      permission = Permission.find(params[:permission_id])

      if permission.present?
        user_permit = UserPermit.find_by(source: @partner_user, permission: permission)
        if user_permit.present?
          redirect_to backoffice_partner_user_path(@partner_user), notice: "Partner User was have assigned APIs Permission for #{permission.name} before."
        else
          user_permit = UserPermit.new(source: @partner_user, permission: permission)
          if user_permit.save
            redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully added new APIs Permission.'
          else
            @url = save_permission_backoffice_partner_user_path(@partner_user)
            flash[:alert] = user_permit.errors.full_messages
            render :add_permission
          end
        end
      else
        @url = save_permission_backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :add_permission
      end
    end

    def delete_permission
      @partner_user = PartnerUser.find(params[:id])
      user_permit = UserPermit.find(params[:user_permit_id])
      if user_permit.present? && user_permit.source == @partner_user
        if user_permit.delete
          redirect_to backoffice_partner_user_path(@partner_user), notice: 'Successfully to delete APIs Permission from Partner User.'
        else
          redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
        end
      else
        redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
      end
    end

    private

    def create_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

    def update_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

  end
end

app/controllers/backoffice/products_controller.rb
module Backoffice
  class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
      @products = Product.all.order(updated_at: :desc)
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
      @url = backoffice_products_path(@product)
    end

    def create
      @product = Product.new(create_params)
      if @product.save
          redirect_to backoffice_product_path(@product), notice: 'Product was successfully created.'
      else
        @url = backoffice_products_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :new
      end
    end

    def edit
      @product = Product.find(params[:id])
      @url = backoffice_product_path(@product)
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(update_params)
        redirect_to backoffice_product_path(@product), notice: 'Product was successfully updated.'
      else
        @url = backoffice_product_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :edit
      end
    end

    private

    def create_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end

    def update_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end
  end
end

app/views/backoffice/orders/index.html.erb
<h1 class="mt-4">Order</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item active">Order</li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    List of Order
  </div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Fullname</th>
          <th scope="col">Address</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Created At</th>
          <th scope="col">Updated At</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
        <tr>
          <th scope="row"><%= order.id %></th>
          <td><%= order.fullname %></td>
          <td><%= order.address %></td>
          <td><%= order.phone %></td>
          <td><%= order.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td><%= order.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td><%= link_to 'Show', backoffice_order_path(order)%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/backoffice/orders/show.html.erb
<h1 class="mt-4">Order</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Order</li>
  <li class="breadcrumb-item active"><%= @order.id %></li>
</ol>

<div class="row">
  <div class="col-xl-3">
    <div class="card mb-4">
      <div class="card-header">User Detail</div>
      <div class="card-body">
        <table class="table table-borderless">
        <thead>
          <tr>
            <td>Fullname</td>
            <td><%= @order.fullname %></td>
          </tr>
          <tr>
            <td>Address</td>
            <td><%= @order.address %></td>
          </tr>
          <tr>
            <td>Phone Number</td>
            <td><%= @order.phone %></td>
          </tr>
          <tr>
            <td>Created At</td>
            <td><%= @order.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
          <tr>
            <td>Updated At</td>
            <td><%= @order.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
        </thead>
      </table>
      </div>
    </div>
  </div>

  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Products Order</div>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product Name</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
            </tr>
          </thead>
          <tbody>
            <% @order.order_items.each_with_index do |order_item, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= order_item.product.title %></td>
                <td><%= order_item.product.price %></td>
                <td><%= order_item.quantity %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>