config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  devise_for :users

  devise_scope :user do
      match "/backoffice"  => "devise/sessions#new", via: [:get], as: :unauthenticated_root
      match "signout" => "devise/sessions#destroy", via: [:delete]
  end

  namespace :backoffice do
    resources :partner_users, except: [:destroy] do
      member do
        get   '/add_permission', to: 'partner_users#add_permission', as: 'add_permission'
        post  '/save_permission', to: 'partner_users#save_permission', as: 'save_permission'
        delete '/permission/:user_permit_id', to: 'partner_users#delete_permission', as: 'delete_permission'
      end
    end
    resources :products, except: [:destroy]
    resources :orders, only: [:index, :show]
    resources :carts, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      # Product
      get 'lists', to: 'products#lists', as: 'list_of_products'
      get 'detail/:id', to: 'products#detail', as: 'detail_of_product'

      # Order
      post 'add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart_order'
      get  'cart/detail/:user_id', to: 'orders#cart_detail', as: 'cart_detail'
      post 'cart/checkout', to: 'orders#checkout', as: 'checkout'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < Api::V1::BaseController

      before_action :authenticate_user, :authorize_request

      def initialize
        super
        @product_service = ::V1::ProductService.new
      end

      def lists
        render_json_result @product_service.lists
      end

      def detail
        if detail_params[:id].present?
          render_json_result @product_service.detail(detail_params[:id])
        else
          render_json_bad_request
        end
      end

      private

      def authorize_request
        authorize_request_for Product
      end

      def detail_params
        params.permit(:id)
      end

    end
  end
end

app/controllers/backoffice/carts_controller.rb
module Backoffice
  class CartsController < ApplicationController
    before_action :authenticate_user!

    def index
      @carts = Cart.all
    end

    def show
      @cart = Cart.find(params[:id])
    end
  end
end

app/controllers/backoffice/orders_controller.rb
module Backoffice
  class OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
      @orders = Order.all
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/backoffice/partner_users_controller.rb
module Backoffice
  class PartnerUsersController < ApplicationController

    before_action :authenticate_user!

    def index
      @partner_users = PartnerUser.all
    end

    def show
      @partner_user = PartnerUser.find(params[:id])
    end

    def new
      @partner_user = PartnerUser.new
      @url = backoffice_partner_users_path(@partner_user)
    end

    def create
      @partner_user = PartnerUser.new(create_params)
      if @partner_user.save
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully created.'
      else
        @url = backoffice_partner_users_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :new
      end
    end

    def edit
      @partner_user = PartnerUser.find(params[:id])
      @url = backoffice_partner_user_path(@partner_user)
    end

    def update
      @partner_user = PartnerUser.find(params[:id])
      if @partner_user.update(update_params)
        redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully updated.'
      else
        @url = backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :edit
      end
    end

    def add_permission
      @partner_user = PartnerUser.find(params[:id])
      @permission_options = Permission.all.collect{ |p| [p.name, p.id]}
      @url = save_permission_backoffice_partner_user_path(@partner_user)
    end

    def save_permission
      @partner_user = PartnerUser.find(params[:id])
      permission = Permission.find(params[:permission_id])

      if permission.present?
        user_permit = UserPermit.find_by(source: @partner_user, permission: permission)
        if user_permit.present?
          redirect_to backoffice_partner_user_path(@partner_user), notice: "Partner User was have assigned APIs Permission for #{permission.name} before."
        else
          user_permit = UserPermit.new(source: @partner_user, permission: permission)
          if user_permit.save
            redirect_to backoffice_partner_user_path(@partner_user), notice: 'Partner User was successfully added new APIs Permission.'
          else
            @url = save_permission_backoffice_partner_user_path(@partner_user)
            flash[:alert] = user_permit.errors.full_messages
            render :add_permission
          end
        end
      else
        @url = save_permission_backoffice_partner_user_path(@partner_user)
        flash[:alert] = @partner_user.errors.full_messages
        render :add_permission
      end
    end

    def delete_permission
      @partner_user = PartnerUser.find(params[:id])
      user_permit = UserPermit.find(params[:user_permit_id])
      if user_permit.present? && user_permit.source == @partner_user
        if user_permit.delete
          redirect_to backoffice_partner_user_path(@partner_user), notice: 'Successfully to delete APIs Permission from Partner User.'
        else
          redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
        end
      else
        redirect_to backoffice_partner_user_path(@partner_user), alert: 'Failed to delete APIs Permission from Partner User.'
      end
    end

    private

    def create_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

    def update_params
      params.require(:partner_user).permit(:fullname, :phone, :address)
    end

  end
end

app/controllers/backoffice/products_controller.rb
module Backoffice
  class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
      @products = Product.all.order(updated_at: :desc)
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
      @url = backoffice_products_path(@product)
    end

    def create
      @product = Product.new(create_params)
      if @product.save
          redirect_to backoffice_product_path(@product), notice: 'Product was successfully created.'
      else
        @url = backoffice_products_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :new
      end
    end

    def edit
      @product = Product.find(params[:id])
      @url = backoffice_product_path(@product)
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(update_params)
        redirect_to backoffice_product_path(@product), notice: 'Product was successfully updated.'
      else
        @url = backoffice_product_path(@product)
        flash[:alert] = @product.errors.full_messages
        render :edit
      end
    end

    private

    def create_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end

    def update_params
      params.require(:product).permit(:title, :price, :picture_tumb, :description)
    end
  end
end

app/views/backoffice/products/_form.html.erb
<%= form_for(@product, url: @url, html: {class: 'form-horizontal'}) do |f| %>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Title</label>
    <div class="col-sm-10">
      <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title', required: true %>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Price</label>
    <div class="col-sm-10">
      <%= f.text_field :price, autofocus: true, class: 'form-control', placeholder: 'Price', required: true %>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Picture</label>
    <div class="col-sm-10">
      <%= f.text_field :picture_tumb, autofocus: true, class: 'form-control', placeholder: 'Picture', required: true %>
    </div>
  </div>
  <div class="mb-3 row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <%= f.text_area :description, autofocus: true, class: 'form-control', placeholder: 'Description' %>
    </div>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %> <%= link_to 'Cancel', backoffice_products_path, class: 'btn btn-secondary' %>
<% end %>

app/views/backoffice/products/edit.html.erb
<h1 class="mt-4">Product</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Product</li>
  <li class="breadcrumb-item"><%= @product.title %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Edit</div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/products/index.html.erb
<h1 class="mt-4">Product</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item active">Product</li>
</ol>

<p><%= link_to 'New', new_backoffice_product_path, class: 'btn btn-primary' %></p>

<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table me-1"></i>
    List of Product
  </div>

  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Price</th>
          <th scope="col">Created At</th>
          <th scope="col">Updated At</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @products.each_with_index do |product, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= product.title %></td>
          <td><%= product.price %></td>
          <td><%= product.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td><%= product.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          <td><%= link_to 'Show', backoffice_product_path(product)%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/backoffice/products/new.html.erb
<h1 class="mt-4">Product</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Product</li>
  <li class="breadcrumb-item active">New</li>
</ol>

<div class="row">
  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Create new</div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/products/show.html.erb
<h1 class="mt-4">Product</h1>
<ol class="breadcrumb mb-4">
  <li class="breadcrumb-item">Product</li>
  <li class="breadcrumb-item active"><%= @product.title %></li>
</ol>

<p><%= link_to 'Edit', edit_backoffice_product_path(@product), class: 'btn btn-warning' %></p>

<div class="row">
  <div class="col-xl-3">
    <div class="card mb-4">
      <div class="card-header">User Detail</div>
      <div class="card-body">
        <table class="table table-borderless">
        <thead>
          <tr>
            <td>Title</td>
            <td><%= @product.title %></td>
          </tr>
          <tr>
            <td>Price</td>
            <td><%= @product.price %></td>
          </tr>
          <tr>
            <td>Description</td>
            <td><%= @product.description %></td>
          </tr>
          <tr>
            <td>Created At</td>
            <td><%= @product.created_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
          <tr>
            <td>Updated At</td>
            <td><%= @product.updated_at.in_time_zone("Jakarta").strftime("%d %b %Y %H:%M") %></td>
          </tr>
        </thead>
      </table>
      </div>
    </div>
  </div>

  <div class="col-xl-6">
    <div class="card mb-4">
      <div class="card-header">Image</div>
      <div class="card-body">
        <center><%= image_tag(@product.picture_tumb, alt: 'product-image') rescue @product.picture_tumb %></center>
      </div>
    </div>
  </div>
</div>