config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  devise_for :users

  devise_scope :user do
      match "/backoffice"  => "devise/sessions#new", via: [:get], as: :unauthenticated_root
      match "signout" => "devise/sessions#destroy", via: [:delete]
  end

  namespace :backoffice do
    resources :partner_users, except: [:destroy] do
      member do
        get   '/add_permission', to: 'partner_users#add_permission', as: 'add_permission'
        post  '/save_permission', to: 'partner_users#save_permission', as: 'save_permission'
        delete '/permission/:user_permit_id', to: 'partner_users#delete_permission', as: 'delete_permission'
      end
    end
    resources :products, except: [:destroy]
    resources :orders, only: [:index, :show]
    resources :carts, only: [:index, :show]
  end

  namespace :api do
    namespace :v1 do
      # Product
      get 'lists', to: 'products#lists', as: 'list_of_products'
      get 'detail/:id', to: 'products#detail', as: 'detail_of_product'

      # Order
      post 'add_to_cart', to: 'orders#add_to_cart', as: 'add_to_cart_order'
      get  'cart/detail/:user_id', to: 'orders#cart_detail', as: 'cart_detail'
      post 'cart/checkout', to: 'orders#checkout', as: 'checkout'
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2021</div>
            <div>
                <%# <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a> %>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>SimpleOpenApi</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" /> %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

app/views/layouts/_side_navigation.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <a class="nav-link" href="index.html">
          <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
          Dashboard
        </a>

        <div class="sb-sidenav-menu-heading">Transaction</div>
        <%= link_to('Order', backoffice_orders_path, { class: "nav-link" }) %>
        <%= link_to('Cart', backoffice_carts_path, { class: "nav-link" }) %>

        <div class="sb-sidenav-menu-heading">Partner</div>
        <%= link_to('Partner User', backoffice_partner_users_path, { class: "nav-link" }) %>

        <div class="sb-sidenav-menu-heading">Product</div>
        <%= link_to('Product', backoffice_products_path, { class: "nav-link" }) %>
      </div>
    </div>
    <div class="sb-sidenav-footer">
      <div class="small">Logged in as:</div>
      <%= current_user.email %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    </div>
  </nav>
</div>

app/views/layouts/_top_navigation.html.erb
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Simple Open-API</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
            </div>
        </form>
        <!-- Navbar-->
        <%# <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul> %>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/top_navigation' %>
    <div id="layoutSidenav">
      <%= render 'layouts/side_navigation' %>
      <div id="layoutSidenav_content">
        <main>
          <div class="container-fluid px-4">
            <%= yield %>
          </div>
        </main>
        <%= render 'layouts/footer' %>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>
    <%= yield %>
  </body>
</html>